apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-app
  labels:
    type: webapp
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: mywebapp
          image: mahendra4518/datastore:v1
  replicas: 2
  selector:
    matchLabels:
      type: webapp
